// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
// ignore: depend_on_referenced_packages
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC7aRwhBdvdbs5OSe1y0OtSkaPCuhXz4yM',
    appId: '1:992124331725:web:af329ee0cd4f4b0ac46b84',
    messagingSenderId: '992124331725',
    projectId: 'chattrial-4b6b5',
    authDomain: 'chattrial-4b6b5.firebaseapp.com',
    storageBucket: 'chattrial-4b6b5.appspot.com',
    measurementId: 'G-4TE5MTS6SM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAd185CP9cSjQbJrg2IuGCvJbsSTCp9EnU',
    appId: '1:992124331725:android:3f10f7b8b95661c9c46b84',
    messagingSenderId: '992124331725',
    projectId: 'chattrial-4b6b5',
    storageBucket: 'chattrial-4b6b5.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB0ZrHq1mvhsvD8uCtCf7qiRaD4q6l8Cok',
    appId: '1:992124331725:ios:4c5c69abd328e9f0c46b84',
    messagingSenderId: '992124331725',
    projectId: 'chattrial-4b6b5',
    storageBucket: 'chattrial-4b6b5.appspot.com',
    iosBundleId: 'com.example.chatApp',
  );
}
